name: nest_doc
channels:
- defaults
- conda-forge
- bioconda
dependencies:
- cmake
- commonmark
- cython==0.23.4
- gsl
- idna
- jinja2
- jupyter
- libffi
- libgcc-ng # Linux only
- libstdcxx-ng # Linux only
- markupsafe
- ncurses=5.9
- nest-simulator
- numpydoc
- openssl
- path.py
- pillow
- pycparser
- pygments
- pyopenssl
- pysocks
- pytest
- python>=3.5
- pytz
- readline=6.2
- setuptools
- sphinxcontrib
- sphinxcontrib-websupport
- sphinx_rtd_theme
- sqlite
- statsmodels
- tk
- typing
- urllib3
- wheel
- xz
- zlib
- pip:
  - example
  - Image
  - nbsphinx
  - recommonmark==0.4.0
  - seaborn
  - sphinx_gallery
  - sphinxcontrib-napoleon
  - mock
  - breathe
